version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - /home/renerecalde/go/src/github.com/renerecalde/simple-rest/Docker/cooperativa.sql:/cooperativa.sql